module.exports = {
  OMILIA_APIKEY: 'OMILIA_APIKEY',
  OMILIA_REGION: 'OMILIA_REGION',
  // Optional:
  OMILIA_USER: 'OMILIA_USER',
  OMILIA_SEMANTICS: 'OMILIA_SEMANTICS',
  OMILIA_INPUT_FIELDS: 'OMILIA_INPUT_FIELDS'
}
